### PR TITLE
Support publicPath in vue.config.js

### LINKED ISSUE #97: Support publicPath in vue.config.js
This setting currently does not work with this plugin: https://cli.vuejs.org/config/#publicpath

I am getting
```
vue.runtime.esm.js:619 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
vue.runtime.esm.js:5861 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at emptyNodeAt (vue.runtime.esm.js:5861)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:6502)
    at VueComponent.Vue._update (vue.runtime.esm.js:3939)
    at VueComponent.updateComponent (vue.runtime.esm.js:4060)
    at Watcher.get (vue.runtime.esm.js:4473)
    at new Watcher (vue.runtime.esm.js:4462)
    at mountComponent (vue.runtime.esm.js:4067)
    at VueComponent../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (vue.runtime.esm.js:8409)
    at init (vue.runtime.esm.js:3118)
    at hydrate (vue.runtime.esm.js:6372)
```

It looks like as if the `<router-view/>` is converted to `<!---->` instead of the view of the current route in the SSR output: 

```
<body>
    <div id="app" data-server-rendered="true"><div id="nav"><a href="/prefix/" class="router-link-active">Home</a> |
    <a href="/prefix/about">About</a></div><!----></div>
    
    
    <script src="/prefix/app.js" defer></script><script src="/prefix/app.d5e9f6709099cd516839.hot-update.js" defer></script>
  </body>
```

So I am assuming that the router does not find a matching route

### PR DESCRIPTION
**Pull request by ulich**
Fixes #97

### CODE REVIEW

**Comment by dennisreimann** [comment]
Some minor additions:

Implementing `prepareUrlForRouting` like this and moving it below the `import` statement in `entry-server.js` would better fit the coding style of this project and also ensure, that the base url works without the trailing slash: 

```js
const prepareUrlForRouting = url => {
  const { BASE_URL } = process.env
  return url.startsWith(BASE_URL.replace(/\/$/, ''))
    ? url.substr(BASE_URL.length)
    : url
}
```

We could also change [this line in `dev-server.js`](https://github.com/Akryum/vue-cli-plugin-ssr/blob/master/lib/dev-server.js#L31) to point to the correct entry url of the app:

```js
const url = `http://localhost:${config.port}${service.projectOptions.publicPath}`
```

When testing this, I found the changes in 2e729de421bd22b3c37600a0aabc09731aa03f56 to not be necessary to make the `publicPath` option work with this plugin. I might be missing something, as the app I'm trying it out with is not very big yet. In case this is necessary I think we should also prepend the `publicPath` [in this line](https://github.com/Akryum/vue-cli-plugin-ssr/blob/2e729de421bd22b3c37600a0aabc09731aa03f56/lib/app.js#L147) like that:

```js
app.get(`${publicPath}*`, (req, res, next) => {
  if (config.skipRequests(req)) {
    return next()
  }
  ssr(req, res)
})
```

**Comment by ulich** [comment]
I will adapt my PR with your remarks.

About:
> When testing this, I found the changes in 2e729de to not be necessary to make the publicPath option work with this plugin.

This only happens when running the production build. The requests to download the javascript bundle all return the html content of the page instead of the static files.

**Comment by dennisreimann** [comment]
I have this PR running in our project and tested it to the extend of our needs. AFAIK this seems good to go 👍

**Comment by dennisreimann** [comment]
fyi: While we are waiting for this to get merged I've published a [fork](https://github.com/dennisreimann/vue-cli-plugin-ssr) on npm, which includes this and other PRs.

Looking forward to seeing this merged!

**Comment by Akryum** [comment]
:+1:

**Pull request merged**
